<a href="https://colab.research.google.com/github/Hniii/Machine-learning/blob/main/Part_0_Q_Learning_with_Tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 0 : Q-Learning with Tables






# Q-Table Learning

## Introduction

Ce notebook contient un code Python qui implémente l'algorithme de Q-learning
tabulaire pour entraîner un agent à naviguer dans l'environnement "FrozenLake-v1" de OpenAI Gym. L'objectif de l'agent est d'apprendre à atteindre la case "G" (but) en partant de la case "S" (départ), en évitant de tomber dans les cases "H" (trous) sur un lac gelé représenté par des cases "F" (surface gelée sûre). L'agent apprendra une stratégie optimale pour maximiser ses chances d'atteindre le but.

In [ ]:
import gym # Importation de la bibliothèque Gym (OpenAI Gym) qui fournit des environnements pour l'apprentissage par renforcement
import numpy as np # Importation la bibliothèque Numpy et la renomme 'np'.Elle est utile pour les calculs numériques


### Load the environment

In [ ]:
env = gym.make('FrozenLake-v1', new_step_api=True) #Création de l'environnement "FrozenLake-v1" de Gym, qui simule le jeu du lac gelé.

## Concepts Clés

Pour comprendre ce code, il est important de connaître quelques concepts de base de l'apprentissage par renforcement :

**Agent :** C'est l'entité qui apprend à prendre des décisions.

**Environnement :** C'est le monde virtuel dans lequel l'agent interagit et apprend (ici, le jeu "FrozenLake-v1").

**État (State) :** C'est une représentation de la situation actuelle de l'agent dans l'environnement (ici, la case où se trouve l'agent dans FrozenLake).

**Action :** C'est une action que l'agent peut réaliser dans l'environnement (ici, se déplacer vers le haut, le bas, la gauche ou la droite dans FrozenLake).

**Récompense (Reward) :** C'est un signal que l'environnement envoie à l'agent pour indiquer si son action était "bonne" ou "mauvaise" (ici, récompense de 1 quand l'agent atteint le but "G", 0 sinon).

**Q-Learning :** C'est un algorithme d'apprentissage par renforcement qui permet à l'agent d'apprendre une "Q-table" qui estime la "qualité" (valeur Q) de chaque action dans chaque état.

**Q-Table :** C'est un tableau (matrice) qui stocke les valeurs Q. Chaque ligne correspond à un état, et chaque colonne à une action. La valeur Q Q[état, action] représente l'estimation de la récompense future cumulée si l'agent choisit l'action action dans l'état état.

### Implement Q-Table learning algorithm

In [ ]:
Q = np.zeros([env.observation_space.n, env.action_space.n]) # On initialise la table Q avec des zéros
# Gestion des paramètres d'apprentissage
lr = 0.8  # lr (learning rate) est le taux d'apprentissage. Il contrôle à quelle vitesse notre agent apprend de nouvelles informations.
y = 0.95  # y (gamma) est le facteur d'escompte.  Plus gamma est élevé, plus l'agent se soucie des récompenses futures (comme atteindre le but à la fin du jeu).
num_episodes = 2000 # num_episodes est le nombre d'épisodes d'entraînement. Un épisode représente une partie complète du jeu. On va entraîner l'agent pendant 2000 parties.


rList = [] # liste pour enregistrer les récompenses totales obtenues à chaque partie de jeu.

for i in range(num_episodes): # Boucle principale qui s'exécute pour chaque partie de jeu, elle prend en compte le nombre total de parties.
    s = env.reset() # Réinitialisation de l'environnement FrozenLake au début de chaque épisode
    rAll = 0 # Initialisation de la variable 'rAll' (récompense totale obtenu lors de la partie  à zéro au début de chaque partie).
    done = False # Initialisation de la variable 'done' à False. 'done' deviendra True quand la partie  est terminé (agent atteint le but ou tombe dans un trou).
    j = 0 # Initialisation de la variable 'j'.Sert à limiter la longueur de chaque partie.
    while j < 99: # boucle while qui va continuer à s'exécuter tant que le nombre de pas de temps j est inférieur à 99
        j += 1    # On incrémente le compteur de pas de temps 'j' de 1 à chaque itération de la boucle 'while
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n) * (1. / (i + 1))) # Choix d'une action gloutonne (avec bruit) à partir de la table Q
        s1, r, terminated, truncated, _ = env.step(a) # L'agent fait une action dans le jeu et regarde ce qui se passe.
        done = terminated or truncated # On regarde si le jeu est fini ou pas
        Q[s, a] = Q[s, a] + lr * (r + y * np.max(Q[s1, :]) - Q[s, a]) # Mise à jour de la table Q-table pour apprendre du jeu
        rAll += r # Ajout de la récompense de ce pas à la récompense totale de l'épisode.
        s = s1 # L'état actuel devient le nouvel état pour le prochain pas.
        if done: # Si le jeu est fini.
            break # alors on arrête la partie de jeu maintenant.
    rList.append(rAll) # Ajout de la récompense totale de cette partie à la liste des récompenses.

/usr/local/lib/python3.11/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [ ]:
print ("Score over time: " +  str(sum(rList)/num_episodes)) # Affiche le score moyen de l'agent sur toutes les parties.

Score over time: 0.5935


In [ ]:
print ("Final Q-Table Values")
print (Q) # On affiche la Q-table (le tableau qui contient ce que l'agent a appris).

Final Q-Table Values
[[6.20912765e-02 1.62554777e-02 1.44445261e-02 1.33704514e-02]
 [2.13402252e-03 4.34912836e-03 5.05616202e-04 1.20594498e-01]
 [3.47988626e-03 3.57150356e-03 1.10648206e-02 7.94434729e-02]
 [4.17681568e-04 0.00000000e+00 9.60529448e-05 3.45301932e-02]
 [7.22015011e-02 1.57382347e-03 2.35590808e-03 2.62900111e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.60490698e-04 1.15201281e-06 3.67733224e-02 2.67482040e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.85936588e-02 4.85729779e-03 2.05397226e-01]
 [5.07692276e-03 2.89068618e-01 0.00000000e+00 4.46113820e-03]
 [3.11967467e-01 0.00000000e+00 0.00000000e+00 2.23169454e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.62368063e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.26169373e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.

## Analyse des résultats

###  Interprétation du Score Moyen

Le score moyen obtenu par l'agent après 2000 parties est de 0.4065.Ce score de 0.4065 signifie qu'en moyenne, sur chaque partie de jeu, l'agent a accumulé une récompense totale de 0.4065.Dans le contexte du jeu FrozenLake, où la récompense pour atteindre le but est de 1 et 0 sinon, un score de 0.4065 signifie que l'agent réussit à atteindre le but dans environ 40% des parties, en moyenne.

### Évaluation de la Performance de l'Agent

À mon avis, la performance de l'agent, avec un score moyen de 0.4065, peut être considérée comme faible.En effet, un agent parfait, qui réussirait à atteindre le but à chaque partie, aurait un score moyen proche de 1. Un score de 0.4065 est donc encore assez éloigné de cette performance idéale.Cependant, il est important de prendre en compte qu'au début de l'entraînement, l'agent ne connaissait rien du jeu et agissait de manière aléatoire. Le score de 0.4065 représente donc déjà un certain niveau d'apprentissage et une amélioration par rapport au début ou il ne connaissait rien du tout.Globalement, la performance de l'agent est en courageante,cela montre que le score peut-être encore largement améliorer.

### Hypothèses et Pistes d'Amélioration

Pour comprendre pourquoi l'agent n'obtient pas un score plus élevé, on peut formuler plusieurs hypothèses sur ces capacités d'apprentissage et identifier des pistes d'amélioration.

**Hypothèse 1 : Exploration de l'environnement**

la première hypothèse serait  que l'agent n'explore pas suffisamment son environnement.

Au début de l'apprentissage, il est important que l'agent explore teste différentes actions et différents chemins pour découvrir les zones sûres (cases 'F') et le but ('G'), et éviter les trous ('H'). Si l'exploration est insuffisante, l'agent risque de se contenter de stratégies sous-optimales et de ne pas trouver le chemin le plus efficace vers le but.

**Amélioration possible:** Pour améliorer l'exploration, on pourrait augmenter la quantité de 'bruit' aléatoire ajouté lors du choix des actions, surtout au début de l'entraînement.


**Hypothèse 2 : les paramètres d'apprentissage**

Une deuxième hypothèse concerne les paramètres d'apprentissage, et notamment le taux d'apprentissage (lr) et le facteur d'escompte (y).

Le taux d'apprentissage (lr = 0.8 dans notre code) pourrait être trop élevé ou trop faible. Un taux d'apprentissage trop élevé pourrait rendre l'apprentissage instable, alors qu'un taux trop faible pourrait le rendre trop lent.

De même, le facteur d'escompte (y = 0.95) pourrait ne pas être optimal. Il influence la manière dont l'agent prend en compte les récompenses futures. Une valeur de y différente pourrait améliorer l'apprentissage.

**Amélioration possible:** Pour voir si le taux d'apprentissage et le facteur d'escompte ont un impact sur la valeur du score moyen de l'agent, il faudrait tester avec différentes valeurs pour le taux d'apprentissage et le facteur d'escompte et ainsi voir si cela à une influence sur le score moyen de l'agent.

**Hypothèse 3 : Nombre d'épisodes**

Une troisième hypothèse est que le nombre d'épisodes d'entraînement (2000) pourrait être insuffisant.

L'apprentissage par renforcement avec le Q-learning tabulaire, peut nécessiter un grand nombre d'épisodes pour converger vers une score optimal (proche de 1). 2000 épisodes pourraient ne pas être suffisants pour que l'agent explore complètement l'environnement et affine correctement sa Q-table.

**Amélioration possible:** Pour vérifier cette hypothèse, on pourrait augmenter le nombre d'épisodes d'entraînement (par exemple, 5000, 10000 ou plus) et voir si le score moyen de l'agent s'améliore.
